import = [
  "~/.config/alacritty/themes/gruvbox_material_medium_light.toml"
]

live_config_reload = true


[window]
padding = {x = 10, y = 5}
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.85
blur = true

[font]
normal = { family = "OperatorMono Nerd Font", style = "Regular" }
bold = { style = "Bold"}
italic = {style = "Italic"}
bold_italic = {style = "Bold Italic"}
offset = { x = 0, y = 0}
size = 25
builtin_box_drawing = true
