import = [
  "~/.config/alacritty/themes/gruvbox_light.toml"
]

live_config_reload = true


[window]
padding = {x = 5, y = 5}
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal = { family = "OperatorMono Nerd Font", style = "Book" } 
bold = { style = "Bold"}
italic = {style = "Italic"}
bold_italic = {style = "Bold Italic"}
offset = { x = 1, y = 0}
size = 18
builtin_box_drawing = true
