#!/usr/bin/env bash

# it will be able to run the command without password
# for this to work you must configure sudo such that

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config layout bsp

yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 20

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config window_opacity off
yabai -m config window_topmost off
yabai -m config window_shadow off

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m config auto_balance off
yabai -m config split_ratio 0.5

yabai -m config window_border off

# -- border use: JankyBorders --
yabai -m config window_border off
borders &

# -- rules --
yabai -m rule --add label=musicapp app="^Music$" manage=off space=2
yabai -m rule --add label=wechat app="^WeChat$" manage=off
yabai -m rule --add label=calendar app="^Calendar$" manage=off
yabai -m rule --add label=sysprefs app="^System Settings$" manage=off
yabai -m rule --add label=finder app="^Finder$" manage=off
yabai -m rule --add label=iina app="^IINA$" manage=off

echo "yabai configuration loaded.."
