#!/bin/bash

options=(
	style=round
	width=8.0
	hidpi=off
	active_color=0xff775759
	inactive_color=0xff414550
	blacklist='IINA,Finder,访达,Calendar,日历,System Preferences,系统偏好设置,微信,WeChat,Music,音乐'
)

borders "${options[@]}"
